title: Yinkar
email: hkarabas@protonmail.com
description: >- 
  Bir çeşit blog
baseurl: "" 
url: "https://yinkar.github.io" 

github_username:  yinkar

google_analytics: G-5YTC13DE9Y

author: Hüseyin Karabaş

theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-sass-converter


avatar: "https://avatars.githubusercontent.com/u/19232184?v=4"
timezone: "Asia/Istanbul"
lang: "tr"
tagline: "Yazılım Geliştirici"

github:
  username: yinkar

twitter:
  username: hsyn_krb

social:
  name: "Hüseyin Karabaş"
  email: hkarabas@yandex.com
  links:
    - https://github.com/yinkar
    - https://dribbble.com/yinkar

theme_mode: dark

disqus:
  shortname: yinkar
  
seo:
  name: Hüseyin Karabaş
  type: Person

minima:
  skin: dark

pixelart-images: "/pixelart/images/"
pixelart-thumbs: "/pixelart/thumbs/"

defaults:
  -
    scope:
      path: "resume"
    values:
      sitemap: false
  -
    scope:
      path: "pdfs/**/*.pdf"
    values:
      sitemap: false